/*
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com
 *
 * The version of the OpenAPI document: 1.72.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;

use reqwest;

use super::{Error, configuration};

pub struct ScheduledTransactionsApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl ScheduledTransactionsApiClient {
    pub fn new(configuration: Rc<configuration::Configuration>) -> ScheduledTransactionsApiClient {
        ScheduledTransactionsApiClient {
            configuration,
        }
    }
}

pub trait ScheduledTransactionsApi {
    fn create_scheduled_transaction(&self, budget_id: &str, data: crate::models::PostScheduledTransactionWrapper) -> Result<crate::models::ScheduledTransactionResponse, Error>;
    fn get_scheduled_transaction_by_id(&self, budget_id: &str, scheduled_transaction_id: &str) -> Result<crate::models::ScheduledTransactionResponse, Error>;
    fn get_scheduled_transactions(&self, budget_id: &str, last_knowledge_of_server: Option<i64>) -> Result<crate::models::ScheduledTransactionsResponse, Error>;
}

impl ScheduledTransactionsApi for ScheduledTransactionsApiClient {
    fn create_scheduled_transaction(&self, budget_id: &str, data: crate::models::PostScheduledTransactionWrapper) -> Result<crate::models::ScheduledTransactionResponse, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/budgets/{budget_id}/scheduled_transactions", configuration.base_path, budget_id=crate::apis::urlencode(budget_id));
        let mut req_builder = client.post(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.bearer_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        req_builder = req_builder.json(&data);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_scheduled_transaction_by_id(&self, budget_id: &str, scheduled_transaction_id: &str) -> Result<crate::models::ScheduledTransactionResponse, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/budgets/{budget_id}/scheduled_transactions/{scheduled_transaction_id}", configuration.base_path, budget_id=crate::apis::urlencode(budget_id), scheduled_transaction_id=crate::apis::urlencode(scheduled_transaction_id));
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.bearer_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_scheduled_transactions(&self, budget_id: &str, last_knowledge_of_server: Option<i64>) -> Result<crate::models::ScheduledTransactionsResponse, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/budgets/{budget_id}/scheduled_transactions", configuration.base_path, budget_id=crate::apis::urlencode(budget_id));
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = last_knowledge_of_server {
            req_builder = req_builder.query(&[("last_knowledge_of_server", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.bearer_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

}
